// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh0S8P98ZrB7lkL_RuvEElaB_1lcSZTXw',
    appId: '1:324924756617:web:2eb1ebb43f8635e1616c58',
    messagingSenderId: '324924756617',
    projectId: 'colijet',
    authDomain: 'colijet.firebaseapp.com',
    storageBucket: 'colijet.appspot.com',
    measurementId: 'G-VJ1NC4ZX9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpuMVgodvDHwSYcMJDCwCjlpED6s35d-Q',
    appId: '1:324924756617:android:6854d23ff1d36399616c58',
    messagingSenderId: '324924756617',
    projectId: 'colijet',
    storageBucket: 'colijet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtmU_c5edpY7uh2bKUsb31XN32LJsWnVo',
    appId: '1:324924756617:ios:143f5a15f8c03f30616c58',
    messagingSenderId: '324924756617',
    projectId: 'colijet',
    storageBucket: 'colijet.appspot.com',
    iosClientId: '324924756617-nad925n2peip77np6ifr6eu9e7dgm6t2.apps.googleusercontent.com',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtmU_c5edpY7uh2bKUsb31XN32LJsWnVo',
    appId: '1:324924756617:ios:143f5a15f8c03f30616c58',
    messagingSenderId: '324924756617',
    projectId: 'colijet',
    storageBucket: 'colijet.appspot.com',
    iosClientId: '324924756617-nad925n2peip77np6ifr6eu9e7dgm6t2.apps.googleusercontent.com',
    iosBundleId: 'com.example.note',
  );
}
